#pragma warning disable S1192 // String literals should not be duplicated

using System.Collections.Generic;
using System.Linq;
using TenjinX.Extensions;

namespace TenjinX.Utilities;

/// <summary>
/// A collection of Mimetype utilities.
/// </summary>
public static class TenjinMimeTypeUtilities
{
    private const char FileExtensionDelimiter = '.';

    private static readonly IDictionary<string, string> FileExtensionToMimeTypeMap = PopulateFileExtensionToMimeTypeMap();
    private static readonly IDictionary<string, IEnumerable<string>> MimeTypeToFileExtensionsMap = PopulateMimeTypeToFileExtensionsMap();

    /// <summary>
    /// Gets the MIME type for a file extension.
    /// </summary>
    public static string? GetMimeType(string fileExtension)
    {
        if (fileExtension.IsEmpty())
        {
            return null;
        }

        var key = fileExtension.StartsWith(FileExtensionDelimiter)
            ? fileExtension.ToLower()
            : $"{FileExtensionDelimiter}{fileExtension.ToLower()}";

        return FileExtensionToMimeTypeMap.TryGetValue(key, out var value)
            ? value
            : null;
    }

    /// <summary>
    /// Gets the common file extension for a MIME type.
    /// </summary>
    public static string? GetFileExtension(string mimeType)
    {
        if (mimeType.IsEmpty())
        {
            return null;
        }

        var key = mimeType.ToLower();

        return MimeTypeToFileExtensionsMap.TryGetValue(key, out var fileExtensions)
            ? fileExtensions.First()
            : null;
    }

    /// <summary>
    /// Gets all file extensions for a MIME type.
    /// </summary>
    public static IEnumerable<string> GetAllFileExtensions(string mimeType)
    {
        if (mimeType.IsEmpty())
        {
            return [];
        }

        var key = mimeType.ToLower();

        return MimeTypeToFileExtensionsMap.TryGetValue(key, out var fileExtensions)
            ? fileExtensions
            : [];
    }

    #region File Extensions To Mime Types Map

    private static IDictionary<string, string> PopulateFileExtensionToMimeTypeMap()
    {
        return new Dictionary<string, string>
        {
            { ".123", "application/vnd.lotus-1-2-3" },
            { ".3dml", "text/vnd.in3d.3dml" },
            { ".3g2", "video/3gpp2" },
            { ".3gp", "video/3gpp" },
            { ".7z", "application/x-7z-compressed" },
            { ".a", "application/octet-stream" },
            { ".aab", "application/x-authorware-bin" },
            { ".aac", "audio/x-aac" },
            { ".aam", "application/x-authorware-map" },
            { ".aas", "application/x-authorware-seg" },
            { ".abw", "application/x-abiword" },
            { ".acc", "application/vnd.americandynamics.acc" },
            { ".ace", "application/x-ace-compressed" },
            { ".acu", "application/vnd.acucobol" },
            { ".acutc", "application/vnd.acucorp" },
            { ".adp", "audio/adpcm" },
            { ".aep", "application/vnd.audiograph" },
            { ".afm", "application/x-font-type1" },
            { ".afp", "application/vnd.ibm.modcap" },
            { ".ai", "application/postscript" },
            { ".aif", "audio/x-aiff" },
            { ".aifc", "audio/x-aiff" },
            { ".aiff", "audio/x-aiff" },
            { ".air", "application/vnd.adobe.air-application-installer-package+zip" },
            { ".ami", "application/vnd.amiga.ami" },
            { ".apk", "application/vnd.android.package-archive" },
            { ".application", "application/x-ms-application" },
            { ".apr", "application/vnd.lotus-approach" },
            { ".asc", "application/pgp-signature" },
            { ".asf", "video/x-ms-asf" },
            { ".asm", "text/x-asm" },
            { ".aso", "application/vnd.accpac.simply.aso" },
            { ".asx", "video/x-ms-asf" },
            { ".atc", "application/vnd.acucorp" },
            { ".atom", "application/atom+xml" },
            { ".atomcat", "application/atomcat+xml" },
            { ".atomsvc", "application/atomsvc+xml" },
            { ".atx", "application/vnd.antix.game-component" },
            { ".au", "audio/basic" },
            { ".avi", "video/x-msvideo" },
            { ".avif", "image/avif" },
            { ".aw", "application/applixware" },
            { ".azf", "application/vnd.airzip.filesecure.azf" },
            { ".azs", "application/vnd.airzip.filesecure.azs" },
            { ".azw", "application/vnd.amazon.ebook" },
            { ".bat", "application/x-msdownload" },
            { ".bcpio", "application/x-bcpio" },
            { ".bdf", "application/x-font-bdf" },
            { ".bdm", "application/vnd.syncml.dm+wbxml" },
            { ".bh2", "application/vnd.fujitsu.oasysprs" },
            { ".bin", "application/octet-stream" },
            { ".bmi", "application/vnd.bmi" },
            { ".bmp", "image/bmp" },
            { ".book", "application/vnd.framemaker" },
            { ".box", "application/vnd.previewsystems.box" },
            { ".boz", "application/x-bzip2" },
            { ".bpk", "application/octet-stream" },
            { ".btif", "image/prs.btif" },
            { ".bz", "application/x-bzip" },
            { ".bz2", "application/x-bzip2" },
            { ".c", "text/x-c" },
            { ".c4d", "application/vnd.clonk.c4group" },
            { ".c4f", "application/vnd.clonk.c4group" },
            { ".c4g", "application/vnd.clonk.c4group" },
            { ".c4p", "application/vnd.clonk.c4group" },
            { ".c4u", "application/vnd.clonk.c4group" },
            { ".cab", "application/vnd.ms-cab-compressed" },
            { ".car", "application/vnd.curl.car" },
            { ".cat", "application/vnd.ms-pki.seccat" },
            { ".cbor", "application/cbor" },
            { ".cc", "text/x-c" },
            { ".cct", "application/x-director" },
            { ".ccxml", "application/ccxml+xml" },
            { ".cdbcmsg", "application/vnd.contact.cmsg" },
            { ".cdf", "application/x-netcdf" },
            { ".cdkey", "application/vnd.mediastation.cdkey" },
            { ".cdx", "chemical/x-cdx" },
            { ".cdxml", "application/vnd.chemdraw+xml" },
            { ".cdy", "application/vnd.cinderella" },
            { ".cer", "application/pkix-cert" },
            { ".cgm", "image/cgm" },
            { ".chat", "application/x-chat" },
            { ".chm", "application/vnd.ms-htmlhelp" },
            { ".chrt", "application/vnd.kde.kchart" },
            { ".cif", "chemical/x-cif" },
            { ".cii", "application/vnd.anser-web-certificate-issue-initiation" },
            { ".cil", "application/vnd.ms-artgalry" },
            { ".cla", "application/vnd.claymore" },
            { ".class", "application/java-vm" },
            { ".clkk", "application/vnd.crick.clicker.keyboard" },
            { ".clkp", "application/vnd.crick.clicker.palette" },
            { ".clkt", "application/vnd.crick.clicker.template" },
            { ".clkw", "application/vnd.crick.clicker.wordbank" },
            { ".clkx", "application/vnd.crick.clicker" },
            { ".clp", "application/x-msclip" },
            { ".cmc", "application/vnd.cosmocaller" },
            { ".cmdf", "chemical/x-cmdf" },
            { ".cml", "chemical/x-cml" },
            { ".cmp", "application/vnd.yellowriver-custom-menu" },
            { ".cmx", "image/x-cmx" },
            { ".cod", "application/vnd.rim.cod" },
            { ".com", "application/x-msdownload" },
            { ".conf", "text/plain" },
            { ".cpio", "application/x-cpio" },
            { ".cpp", "text/x-c" },
            { ".cpt", "application/mac-compactpro" },
            { ".crd", "application/x-mscardfile" },
            { ".crl", "application/pkix-crl" },
            { ".crt", "application/x-x509-ca-cert" },
            { ".csh", "application/x-csh" },
            { ".csml", "chemical/x-csml" },
            { ".csp", "application/vnd.commonspace" },
            { ".css", "text/css" },
            { ".cst", "application/x-director" },
            { ".csv", "text/csv" },
            { ".cu", "application/cu-seeme" },
            { ".curl", "text/vnd.curl" },
            { ".cww", "application/prs.cww" },
            { ".cxt", "application/x-director" },
            { ".cxx", "text/x-c" },
            { ".daf", "application/vnd.mobius.daf" },
            { ".dataless", "application/vnd.fdsn.seed" },
            { ".davmount", "application/davmount+xml" },
            { ".dcr", "application/x-director" },
            { ".dcurl", "text/vnd.curl.dcurl" },
            { ".dd2", "application/vnd.oma.dd2+xml" },
            { ".ddd", "application/vnd.fujixerox.ddd" },
            { ".deb", "application/x-debian-package" },
            { ".def", "text/plain" },
            { ".deploy", "application/octet-stream" },
            { ".der", "application/x-x509-ca-cert" },
            { ".dfac", "application/vnd.dreamfactory" },
            { ".dic", "text/x-c" },
            { ".diff", "text/plain" },
            { ".dir", "application/x-director" },
            { ".dis", "application/vnd.mobius.dis" },
            { ".dist", "application/octet-stream" },
            { ".distz", "application/octet-stream" },
            { ".djv", "image/vnd.djvu" },
            { ".djvu", "image/vnd.djvu" },
            { ".dll", "application/x-msdownload" },
            { ".dmg", "application/octet-stream" },
            { ".dms", "application/octet-stream" },
            { ".dna", "application/vnd.dna" },
            { ".doc", "application/msword" },
            { ".docm", "application/vnd.ms-word.document.macroenabled.12" },
            { ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
            { ".dot", "application/msword" },
            { ".dotm", "application/vnd.ms-word.template.macroenabled.12" },
            { ".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template" },
            { ".dp", "application/vnd.osgi.dp" },
            { ".dpg", "application/vnd.dpgraph" },
            { ".dsc", "text/prs.lines.tag" },
            { ".dtb", "application/x-dtbook+xml" },
            { ".dtd", "application/xml-dtd" },
            { ".dts", "audio/vnd.dts" },
            { ".dtshd", "audio/vnd.dts.hd" },
            { ".dump", "application/octet-stream" },
            { ".dvi", "application/x-dvi" },
            { ".dwf", "model/vnd.dwf" },
            { ".dwg", "image/vnd.dwg" },
            { ".dxf", "image/vnd.dxf" },
            { ".dxp", "application/vnd.spotfire.dxp" },
            { ".dxr", "application/x-director" },
            { ".ecelp4800", "audio/vnd.nuera.ecelp4800" },
            { ".ecelp7470", "audio/vnd.nuera.ecelp7470" },
            { ".ecelp9600", "audio/vnd.nuera.ecelp9600" },
            { ".ecma", "application/ecmascript" },
            { ".edm", "application/vnd.novadigm.edm" },
            { ".edx", "application/vnd.novadigm.edx" },
            { ".efif", "application/vnd.picsel" },
            { ".ei6", "application/vnd.pg.osasli" },
            { ".elc", "application/octet-stream" },
            { ".eml", "message/rfc822" },
            { ".emma", "application/emma+xml" },
            { ".eol", "audio/vnd.digital-winds" },
            { ".eot", "application/vnd.ms-fontobject" },
            { ".eps", "application/postscript" },
            { ".epub", "application/epub+zip" },
            { ".es3", "application/vnd.eszigno3+xml" },
            { ".esf", "application/vnd.epson.esf" },
            { ".et3", "application/vnd.eszigno3+xml" },
            { ".etx", "text/x-setext" },
            { ".exe", "application/x-msdownload" },
            { ".ext", "application/vnd.novadigm.ext" },
            { ".ez", "application/andrew-inset" },
            { ".ez2", "application/vnd.ezpix-album" },
            { ".ez3", "application/vnd.ezpix-package" },
            { ".f", "text/x-fortran" },
            { ".f4v", "video/x-f4v" },
            { ".f77", "text/x-fortran" },
            { ".f90", "text/x-fortran" },
            { ".fbs", "image/vnd.fastbidsheet" },
            { ".fdf", "application/vnd.fdf" },
            { ".fe_launch", "application/vnd.denovo.fcselayout-link" },
            { ".fg5", "application/vnd.fujitsu.oasysgp" },
            { ".fgd", "application/x-director" },
            { ".fh", "image/x-freehand" },
            { ".fh4", "image/x-freehand" },
            { ".fh5", "image/x-freehand" },
            { ".fh7", "image/x-freehand" },
            { ".fhc", "image/x-freehand" },
            { ".fig", "application/x-xfig" },
            { ".flac", "audio/flac" },
            { ".fli", "video/x-fli" },
            { ".flo", "application/vnd.micrografx.flo" },
            { ".flv", "video/x-flv" },
            { ".flw", "application/vnd.kde.kivio" },
            { ".flx", "text/vnd.fmi.flexstor" },
            { ".fly", "text/vnd.fly" },
            { ".fm", "application/vnd.framemaker" },
            { ".fnc", "application/vnd.frogans.fnc" },
            { ".for", "text/x-fortran" },
            { ".fpx", "image/vnd.fpx" },
            { ".frame", "application/vnd.framemaker" },
            { ".fsc", "application/vnd.fsc.weblaunch" },
            { ".fst", "image/vnd.fst" },
            { ".ftc", "application/vnd.fluxtime.clip" },
            { ".fti", "application/vnd.anser-web-funds-transfer-initiation" },
            { ".fvt", "video/vnd.fvt" },
            { ".fzs", "application/vnd.fuzzysheet" },
            { ".g3", "image/g3fax" },
            { ".gac", "application/vnd.groove-account" },
            { ".gdl", "model/vnd.gdl" },
            { ".geo", "application/vnd.dynageo" },
            { ".gex", "application/vnd.geometry-explorer" },
            { ".ggb", "application/vnd.geogebra.file" },
            { ".ggt", "application/vnd.geogebra.tool" },
            { ".ghf", "application/vnd.groove-help" },
            { ".gif", "image/gif" },
            { ".gim", "application/vnd.groove-identity-message" },
            { ".gmx", "application/vnd.gmx" },
            { ".gnumeric", "application/x-gnumeric" },
            { ".gph", "application/vnd.flographit" },
            { ".gqf", "application/vnd.grafeq" },
            { ".gqs", "application/vnd.grafeq" },
            { ".gram", "application/srgs" },
            { ".graphql", "application/graphql" },
            { ".gre", "application/vnd.geometry-explorer" },
            { ".grv", "application/vnd.groove-injector" },
            { ".grxml", "application/srgs+xml" },
            { ".gsf", "application/x-font-ghostscript" },
            { ".gtar", "application/x-gtar" },
            { ".gtm", "application/vnd.groove-tool-message" },
            { ".gtw", "model/vnd.gtw" },
            { ".gv", "text/vnd.graphviz" },
            { ".gz", "application/x-gzip" },
            { ".h", "text/x-c" },
            { ".h261", "video/h261" },
            { ".h263", "video/h263" },
            { ".h264", "video/h264" },
            { ".hbci", "application/vnd.hbci" },
            { ".hdf", "application/x-hdf" },
            { ".heic", "image/heic" },
            { ".heif", "image/heif" },
            { ".hh", "text/x-c" },
            { ".hlp", "application/winhlp" },
            { ".hpgl", "application/vnd.hp-hpgl" },
            { ".hpid", "application/vnd.hp-hpid" },
            { ".hps", "application/vnd.hp-hps" },
            { ".hqx", "application/mac-binhex40" },
            { ".htke", "application/vnd.kenameaapp" },
            { ".htm", "text/html" },
            { ".html", "text/html" },
            { ".hvd", "application/vnd.yamaha.hv-dic" },
            { ".hvp", "application/vnd.yamaha.hv-voice" },
            { ".hvs", "application/vnd.yamaha.hv-script" },
            { ".icc", "application/vnd.iccprofile" },
            { ".ice", "x-conference/x-cooltalk" },
            { ".icm", "application/vnd.iccprofile" },
            { ".ico", "image/x-icon" },
            { ".ics", "text/calendar" },
            { ".ief", "image/ief" },
            { ".ifb", "text/calendar" },
            { ".ifm", "application/vnd.shana.informed.formdata" },
            { ".iges", "model/iges" },
            { ".igl", "application/vnd.igloader" },
            { ".igs", "model/iges" },
            { ".igx", "application/vnd.micrografx.igx" },
            { ".iif", "application/vnd.shana.informed.interchange" },
            { ".imp", "application/vnd.accpac.simply.imp" },
            { ".ims", "application/vnd.ms-ims" },
            { ".in", "text/plain" },
            { ".ipk", "application/vnd.shana.informed.package" },
            { ".irm", "application/vnd.ibm.rights-management" },
            { ".irp", "application/vnd.irepository.package+xml" },
            { ".iso", "application/octet-stream" },
            { ".itp", "application/vnd.shana.informed.formtemplate" },
            { ".ivp", "application/vnd.immervision-ivp" },
            { ".ivu", "application/vnd.immervision-ivu" },
            { ".jad", "text/vnd.sun.j2me.app-descriptor" },
            { ".jam", "application/vnd.jam" },
            { ".jar", "application/java-archive" },
            { ".java", "text/x-java-source" },
            { ".jisp", "application/vnd.jisp" },
            { ".jlt", "application/vnd.hp-jlyt" },
            { ".jnlp", "application/x-java-jnlp-file" },
            { ".joda", "application/vnd.joost.joda-archive" },
            { ".jpe", "image/jpeg" },
            { ".jpeg", "image/jpeg" },
            { ".jpg", "image/jpeg" },
            { ".jpgm", "video/jpm" },
            { ".jpgv", "video/jpeg" },
            { ".jpm", "video/jpm" },
            { ".js", "application/javascript" },
            { ".json", "application/json" },
            { ".jsonld", "application/ld+json" },
            { ".kar", "audio/midi" },
            { ".karbon", "application/vnd.kde.karbon" },
            { ".kfo", "application/vnd.kde.kformula" },
            { ".kia", "application/vnd.kidspiration" },
            { ".kil", "application/x-killustrator" },
            { ".kml", "application/vnd.google-earth.kml+xml" },
            { ".kmz", "application/vnd.google-earth.kmz" },
            { ".kne", "application/vnd.kinar" },
            { ".knp", "application/vnd.kinar" },
            { ".kon", "application/vnd.kde.kontour" },
            { ".kpr", "application/vnd.kde.kpresenter" },
            { ".kpt", "application/vnd.kde.kpresenter" },
            { ".ksh", "text/plain" },
            { ".ksp", "application/vnd.kde.kspread" },
            { ".ktr", "application/vnd.kahootz" },
            { ".ktz", "application/vnd.kahootz" },
            { ".kwd", "application/vnd.kde.kword" },
            { ".kwt", "application/vnd.kde.kword" },
            { ".latex", "application/x-latex" },
            { ".lbd", "application/vnd.llamagraphics.life-balance.desktop" },
            { ".lbe", "application/vnd.llamagraphics.life-balance.exchange+xml" },
            { ".les", "application/vnd.hhe.lesson-player" },
            { ".lha", "application/octet-stream" },
            { ".link66", "application/vnd.route66.link66+xml" },
            { ".list", "text/plain" },
            { ".list3820", "application/vnd.ibm.modcap" },
            { ".listafp", "application/vnd.ibm.modcap" },
            { ".log", "text/plain" },
            { ".lostxml", "application/lost+xml" },
            { ".lrf", "application/octet-stream" },
            { ".lrm", "application/vnd.ms-lrm" },
            { ".ltf", "application/vnd.frogans.ltf" },
            { ".lvp", "audio/vnd.lucent.voice" },
            { ".lwp", "application/vnd.lotus-wordpro" },
            { ".lzh", "application/octet-stream" },
            { ".m13", "application/x-msmediaview" },
            { ".m14", "application/x-msmediaview" },
            { ".m1v", "video/mpeg" },
            { ".m2a", "audio/mpeg" },
            { ".m2v", "video/mpeg" },
            { ".m3a", "audio/mpeg" },
            { ".m3u", "audio/x-mpegurl" },
            { ".m4u", "video/vnd.mpegurl" },
            { ".m4v", "video/x-m4v" },
            { ".ma", "application/mathematica" },
            { ".mag", "application/vnd.ecowin.chart" },
            { ".maker", "application/vnd.framemaker" },
            { ".man", "text/troff" },
            { ".mathml", "application/mathml+xml" },
            { ".mb", "application/mathematica" },
            { ".mbk", "application/vnd.mobius.mbk" },
            { ".mbox", "application/mbox" },
            { ".mc1", "application/vnd.medcalcdata" },
            { ".mcd", "application/vnd.mcd" },
            { ".mcurl", "text/vnd.curl.mcurl" },
            { ".mdb", "application/x-msaccess" },
            { ".mdi", "image/vnd.ms-modi" },
            { ".me", "text/troff" },
            { ".mesh", "model/mesh" },
            { ".mfm", "application/vnd.mfmp" },
            { ".mgz", "application/vnd.proteus.magazine" },
            { ".mht", "message/rfc822" },
            { ".mhtml", "message/rfc822" },
            { ".mid", "audio/midi" },
            { ".midi", "audio/midi" },
            { ".mif", "application/vnd.mif" },
            { ".mime", "message/rfc822" },
            { ".mj2", "video/mj2" },
            { ".mjp2", "video/mj2" },
            { ".mlp", "application/vnd.dolby.mlp" },
            { ".mmd", "application/vnd.chipnuts.karaoke-mmd" },
            { ".mmf", "application/vnd.smaf" },
            { ".mmr", "image/vnd.fujixerox.edmics-mmr" },
            { ".mny", "application/x-msmoney" },
            { ".mobi", "application/x-mobipocket-ebook" },
            { ".mov", "video/quicktime" },
            { ".movie", "video/x-sgi-movie" },
            { ".mp2", "audio/mpeg" },
            { ".mp2a", "audio/mpeg" },
            { ".mp3", "audio/mpeg" },
            { ".mp4", "video/mp4" },
            { ".mp4a", "audio/mp4" },
            { ".mp4s", "application/mp4" },
            { ".mp4v", "video/mp4" },
            { ".mpa", "video/mpeg" },
            { ".mpc", "application/vnd.mophun.certificate" },
            { ".mpe", "video/mpeg" },
            { ".mpeg", "video/mpeg" },
            { ".mpg", "video/mpeg" },
            { ".mpg4", "video/mp4" },
            { ".mpga", "audio/mpeg" },
            { ".mpkg", "application/vnd.apple.installer+xml" },
            { ".mpm", "application/vnd.blueice.multipass" },
            { ".mpn", "application/vnd.mophun.application" },
            { ".mpp", "application/vnd.ms-project" },
            { ".mpt", "application/vnd.ms-project" },
            { ".mpy", "application/vnd.ibm.minipay" },
            { ".mqy", "application/vnd.mobius.mqy" },
            { ".mrc", "application/marc" },
            { ".ms", "text/troff" },
            { ".mscml", "application/mediaservercontrol+xml" },
            { ".mseed", "application/vnd.fdsn.mseed" },
            { ".mseq", "application/vnd.mseq" },
            { ".msf", "application/vnd.epson.msf" },
            { ".msh", "model/mesh" },
            { ".msi", "application/x-msdownload" },
            { ".msl", "application/vnd.mobius.msl" },
            { ".msty", "application/vnd.muvee.style" },
            { ".mts", "model/vnd.mts" },
            { ".mus", "application/vnd.musician" },
            { ".musicxml", "application/vnd.recordare.musicxml+xml" },
            { ".mvb", "application/x-msmediaview" },
            { ".mwf", "application/vnd.mfer" },
            { ".mxf", "application/mxf" },
            { ".mxl", "application/vnd.recordare.musicxml" },
            { ".mxml", "application/xv+xml" },
            { ".mxs", "application/vnd.triscape.mxs" },
            { ".mxu", "video/vnd.mpegurl" },
            { ".n-gage", "application/vnd.nokia.n-gage.symbian.install" },
            { ".nb", "application/mathematica" },
            { ".nc", "application/x-netcdf" },
            { ".ncx", "application/x-dtbncx+xml" },
            { ".ngdat", "application/vnd.nokia.n-gage.data" },
            { ".nlu", "application/vnd.neurolanguage.nlu" },
            { ".nml", "application/vnd.enliven" },
            { ".nnd", "application/vnd.noblenet-directory" },
            { ".nns", "application/vnd.noblenet-sealer" },
            { ".nnw", "application/vnd.noblenet-web" },
            { ".npx", "image/vnd.net-fpx" },
            { ".nsf", "application/vnd.lotus-notes" },
            { ".nws", "message/rfc822" },
            { ".o", "application/octet-stream" },
            { ".oa2", "application/vnd.fujitsu.oasys2" },
            { ".oa3", "application/vnd.fujitsu.oasys3" },
            { ".oas", "application/vnd.fujitsu.oasys" },
            { ".obd", "application/x-msbinder" },
            { ".obj", "application/octet-stream" },
            { ".oda", "application/oda" },
            { ".odb", "application/vnd.oasis.opendocument.database" },
            { ".odc", "application/vnd.oasis.opendocument.chart" },
            { ".odf", "application/vnd.oasis.opendocument.formula" },
            { ".odft", "application/vnd.oasis.opendocument.formula-template" },
            { ".odg", "application/vnd.oasis.opendocument.graphics" },
            { ".odi", "application/vnd.oasis.opendocument.image" },
            { ".odp", "application/vnd.oasis.opendocument.presentation" },
            { ".ods", "application/vnd.oasis.opendocument.spreadsheet" },
            { ".odt", "application/vnd.oasis.opendocument.text" },
            { ".oga", "audio/ogg" },
            { ".ogg", "audio/ogg" },
            { ".ogv", "video/ogg" },
            { ".ogx", "application/ogg" },
            { ".onepkg", "application/onenote" },
            { ".onetmp", "application/onenote" },
            { ".onetoc", "application/onenote" },
            { ".onetoc2", "application/onenote" },
            { ".opf", "application/oebps-package+xml" },
            { ".oprc", "application/vnd.palm" },
            { ".org", "application/vnd.lotus-organizer" },
            { ".osf", "application/vnd.yamaha.openscoreformat" },
            { ".osfpvg", "application/vnd.yamaha.openscoreformat.osfpvg+xml" },
            { ".otc", "application/vnd.oasis.opendocument.chart-template" },
            { ".otf", "application/x-font-otf" },
            { ".otg", "application/vnd.oasis.opendocument.graphics-template" },
            { ".oth", "application/vnd.oasis.opendocument.text-web" },
            { ".oti", "application/vnd.oasis.opendocument.image-template" },
            { ".otm", "application/vnd.oasis.opendocument.text-master" },
            { ".otp", "application/vnd.oasis.opendocument.presentation-template" },
            { ".ots", "application/vnd.oasis.opendocument.spreadsheet-template" },
            { ".ott", "application/vnd.oasis.opendocument.text-template" },
            { ".oxt", "application/vnd.openofficeorg.extension" },
            { ".p", "text/x-pascal" },
            { ".p10", "application/pkcs10" },
            { ".p12", "application/x-pkcs12" },
            { ".p7b", "application/x-pkcs7-certificates" },
            { ".p7c", "application/pkcs7-mime" },
            { ".p7m", "application/pkcs7-mime" },
            { ".p7r", "application/x-pkcs7-certreqresp" },
            { ".p7s", "application/pkcs7-signature" },
            { ".pas", "text/x-pascal" },
            { ".pbd", "application/vnd.powerbuilder6" },
            { ".pbm", "image/x-portable-bitmap" },
            { ".pcf", "application/x-font-pcf" },
            { ".pcl", "application/vnd.hp-pcl" },
            { ".pclxl", "application/vnd.hp-pclxl" },
            { ".pct", "image/x-pict" },
            { ".pcurl", "application/vnd.curl.pcurl" },
            { ".pcx", "image/x-pcx" },
            { ".pdb", "application/vnd.palm" },
            { ".pdf", "application/pdf" },
            { ".pfa", "application/x-font-type1" },
            { ".pfb", "application/x-font-type1" },
            { ".pfm", "application/x-font-type1" },
            { ".pfr", "application/font-tdpfr" },
            { ".pfx", "application/x-pkcs12" },
            { ".pgm", "image/x-portable-graymap" },
            { ".pgn", "application/x-chess-pgn" },
            { ".pgp", "application/pgp-encrypted" },
            { ".pic", "image/x-pict" },
            { ".pkg", "application/octet-stream" },
            { ".pki", "application/pkixcmp" },
            { ".pkipath", "application/pkix-pkipath" },
            { ".pl", "text/plain" },
            { ".plb", "application/vnd.3gpp.pic-bw-large" },
            { ".plc", "application/vnd.mobius.plc" },
            { ".plf", "application/vnd.pocketlearn" },
            { ".pls", "application/pls+xml" },
            { ".pml", "application/vnd.ctc-posml" },
            { ".png", "image/png" },
            { ".pnm", "image/x-portable-anymap" },
            { ".portpkg", "application/vnd.macports.portpkg" },
            { ".pot", "application/vnd.ms-powerpoint" },
            { ".potm", "application/vnd.ms-powerpoint.template.macroenabled.12" },
            { ".potx", "application/vnd.openxmlformats-officedocument.presentationml.template" },
            { ".ppa", "application/vnd.ms-powerpoint" },
            { ".ppam", "application/vnd.ms-powerpoint.addin.macroenabled.12" },
            { ".ppd", "application/vnd.cups-ppd" },
            { ".ppm", "image/x-portable-pixmap" },
            { ".pps", "application/vnd.ms-powerpoint" },
            { ".ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12" },
            { ".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow" },
            { ".ppt", "application/vnd.ms-powerpoint" },
            { ".pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12" },
            { ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
            { ".pqa", "application/vnd.palm" },
            { ".prc", "application/x-mobipocket-ebook" },
            { ".pre", "application/vnd.lotus-freelance" },
            { ".prf", "application/pics-rules" },
            { ".ps", "application/postscript" },
            { ".psb", "application/vnd.3gpp.pic-bw-small" },
            { ".psd", "image/vnd.adobe.photoshop" },
            { ".psf", "application/x-font-linux-psf" },
            { ".ptid", "application/vnd.pvi.ptid1" },
            { ".pub", "application/x-mspublisher" },
            { ".pvb", "application/vnd.3gpp.pic-bw-var" },
            { ".pwn", "application/vnd.3m.post-it-notes" },
            { ".pwz", "application/vnd.ms-powerpoint" },
            { ".py", "text/x-python" },
            { ".pya", "audio/vnd.ms-playready.media.pya" },
            { ".pyc", "application/x-python-code" },
            { ".pyo", "application/x-python-code" },
            { ".pyv", "video/vnd.ms-playready.media.pyv" },
            { ".qam", "application/vnd.epson.quickanime" },
            { ".qbo", "application/vnd.intu.qbo" },
            { ".qfx", "application/vnd.intu.qfx" },
            { ".qps", "application/vnd.publishare-delta-tree" },
            { ".qt", "video/quicktime" },
            { ".qwd", "application/vnd.quark.quarkxpress" },
            { ".qwt", "application/vnd.quark.quarkxpress" },
            { ".qxb", "application/vnd.quark.quarkxpress" },
            { ".qxd", "application/vnd.quark.quarkxpress" },
            { ".qxl", "application/vnd.quark.quarkxpress" },
            { ".qxt", "application/vnd.quark.quarkxpress" },
            { ".ra", "audio/x-pn-realaudio" },
            { ".ram", "audio/x-pn-realaudio" },
            { ".rar", "application/x-rar-compressed" },
            { ".ras", "image/x-cmu-raster" },
            { ".rcprofile", "application/vnd.ipunplugged.rcprofile" },
            { ".rdf", "application/rdf+xml" },
            { ".rdz", "application/vnd.data-vision.rdz" },
            { ".rep", "application/vnd.businessobjects" },
            { ".res", "application/x-dtbresource+xml" },
            { ".rgb", "image/x-rgb" },
            { ".rif", "application/reginfo+xml" },
            { ".rl", "application/resource-lists+xml" },
            { ".rlc", "image/vnd.fujixerox.edmics-rlc" },
            { ".rld", "application/resource-lists-diff+xml" },
            { ".rm", "application/vnd.rn-realmedia" },
            { ".rmi", "audio/midi" },
            { ".rmp", "audio/x-pn-realaudio-plugin" },
            { ".rms", "application/vnd.jcp.javame.midlet-rms" },
            { ".rnc", "application/relax-ng-compact-syntax" },
            { ".roff", "text/troff" },
            { ".rpm", "application/x-rpm" },
            { ".rpss", "application/vnd.nokia.radio-presets" },
            { ".rpst", "application/vnd.nokia.radio-preset" },
            { ".rq", "application/sparql-query" },
            { ".rs", "application/rls-services+xml" },
            { ".rsd", "application/rsd+xml" },
            { ".rss", "application/rss+xml" },
            { ".rtf", "application/rtf" },
            { ".rtx", "text/richtext" },
            { ".s", "text/x-asm" },
            { ".saf", "application/vnd.yamaha.smaf-audio" },
            { ".sbml", "application/sbml+xml" },
            { ".sc", "application/vnd.ibm.secure-container" },
            { ".scd", "application/x-msschedule" },
            { ".scm", "application/vnd.lotus-screencam" },
            { ".scq", "application/scvp-cv-request" },
            { ".scs", "application/scvp-cv-response" },
            { ".scurl", "text/vnd.curl.scurl" },
            { ".sda", "application/vnd.stardivision.draw" },
            { ".sdc", "application/vnd.stardivision.calc" },
            { ".sdd", "application/vnd.stardivision.impress" },
            { ".sdkd", "application/vnd.solent.sdkm+xml" },
            { ".sdkm", "application/vnd.solent.sdkm+xml" },
            { ".sdp", "application/sdp" },
            { ".sdw", "application/vnd.stardivision.writer" },
            { ".see", "application/vnd.seemail" },
            { ".seed", "application/vnd.fdsn.seed" },
            { ".sema", "application/vnd.sema" },
            { ".semd", "application/vnd.semd" },
            { ".semf", "application/vnd.semf" },
            { ".ser", "application/java-serialized-object" },
            { ".setpay", "application/set-payment-initiation" },
            { ".setreg", "application/set-registration-initiation" },
            { ".sfd-hdstx", "application/vnd.hydrostatix.sof-data" },
            { ".sfs", "application/vnd.spotfire.sfs" },
            { ".sgl", "application/vnd.stardivision.writer-global" },
            { ".sgm", "text/sgml" },
            { ".sgml", "text/sgml" },
            { ".sh", "application/x-sh" },
            { ".shar", "application/x-shar" },
            { ".shf", "application/shf+xml" },
            { ".si", "text/vnd.wap.si" },
            { ".sic", "application/vnd.wap.sic" },
            { ".sig", "application/pgp-signature" },
            { ".silo", "model/mesh" },
            { ".sis", "application/vnd.symbian.install" },
            { ".sisx", "application/vnd.symbian.install" },
            { ".sit", "application/x-stuffit" },
            { ".sitx", "application/x-stuffitx" },
            { ".skd", "application/vnd.koan" },
            { ".skm", "application/vnd.koan" },
            { ".skp", "application/vnd.koan" },
            { ".skt", "application/vnd.koan" },
            { ".sl", "text/vnd.wap.sl" },
            { ".slc", "application/vnd.wap.slc" },
            { ".sldm", "application/vnd.ms-powerpoint.slide.macroenabled.12" },
            { ".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide" },
            { ".slt", "application/vnd.epson.salt" },
            { ".smf", "application/vnd.stardivision.math" },
            { ".smi", "application/smil+xml" },
            { ".smil", "application/smil+xml" },
            { ".snd", "audio/basic" },
            { ".snf", "application/x-font-snf" },
            { ".so", "application/octet-stream" },
            { ".spc", "application/x-pkcs7-certificates" },
            { ".spf", "application/vnd.yamaha.smaf-phrase" },
            { ".spl", "application/x-futuresplash" },
            { ".spot", "text/vnd.in3d.spot" },
            { ".spp", "application/scvp-vp-response" },
            { ".spq", "application/scvp-vp-request" },
            { ".spx", "audio/ogg" },
            { ".src", "application/x-wais-source" },
            { ".srx", "application/sparql-results+xml" },
            { ".sse", "application/vnd.kodak-descriptor" },
            { ".ssf", "application/vnd.epson.ssf" },
            { ".ssml", "application/ssml+xml" },
            { ".stc", "application/vnd.sun.xml.calc.template" },
            { ".std", "application/vnd.sun.xml.draw.template" },
            { ".stf", "application/vnd.wt.stf" },
            { ".sti", "application/vnd.sun.xml.impress.template" },
            { ".stk", "application/hyperstudio" },
            { ".stl", "application/vnd.ms-pki.stl" },
            { ".str", "application/vnd.pg.format" },
            { ".stw", "application/vnd.sun.xml.writer.template" },
            { ".sus", "application/vnd.sus-calendar" },
            { ".susp", "application/vnd.sus-calendar" },
            { ".sv4cpio", "application/x-sv4cpio" },
            { ".sv4crc", "application/x-sv4crc" },
            { ".svd", "application/vnd.svd" },
            { ".svg", "image/svg+xml" },
            { ".svgz", "image/svg+xml" },
            { ".swa", "application/x-director" },
            { ".swf", "application/x-shockwave-flash" },
            { ".swi", "application/vnd.arastra.swi" },
            { ".sxc", "application/vnd.sun.xml.calc" },
            { ".sxd", "application/vnd.sun.xml.draw" },
            { ".sxg", "application/vnd.sun.xml.writer.global" },
            { ".sxi", "application/vnd.sun.xml.impress" },
            { ".sxm", "application/vnd.sun.xml.math" },
            { ".sxw", "application/vnd.sun.xml.writer" },
            { ".t", "text/troff" },
            { ".tao", "application/vnd.tao.intent-module-archive" },
            { ".tar", "application/x-tar" },
            { ".tcap", "application/vnd.3gpp2.tcap" },
            { ".tcl", "application/x-tcl" },
            { ".teacher", "application/vnd.smart.teacher" },
            { ".tex", "application/x-tex" },
            { ".texi", "application/x-texinfo" },
            { ".texinfo", "application/x-texinfo" },
            { ".text", "text/plain" },
            { ".tfm", "application/x-tex-tfm" },
            { ".tgz", "application/x-gzip" },
            { ".tif", "image/tiff" },
            { ".tiff", "image/tiff" },
            { ".tmo", "application/vnd.tmobile-livetv" },
            { ".torrent", "application/x-bittorrent" },
            { ".tpl", "application/vnd.groove-tool-template" },
            { ".tpt", "application/vnd.trid.tpt" },
            { ".tr", "text/troff" },
            { ".tra", "application/vnd.trueapp" },
            { ".trm", "application/x-msterminal" },
            { ".tsv", "text/tab-separated-values" },
            { ".ttc", "application/x-font-ttf" },
            { ".ttf", "application/x-font-ttf" },
            { ".twd", "application/vnd.simtech-mindmapper" },
            { ".twds", "application/vnd.simtech-mindmapper" },
            { ".txd", "application/vnd.genomatix.tuxedo" },
            { ".txf", "application/vnd.mobius.txf" },
            { ".txt", "text/plain" },
            { ".u32", "application/x-authorware-bin" },
            { ".udeb", "application/x-debian-package" },
            { ".ufd", "application/vnd.ufdl" },
            { ".ufdl", "application/vnd.ufdl" },
            { ".umj", "application/vnd.umajin" },
            { ".unityweb", "application/vnd.unity" },
            { ".uoml", "application/vnd.uoml+xml" },
            { ".uri", "text/uri-list" },
            { ".uris", "text/uri-list" },
            { ".urls", "text/uri-list" },
            { ".ustar", "application/x-ustar" },
            { ".utz", "application/vnd.uiq.theme" },
            { ".uu", "text/x-uuencode" },
            { ".vcd", "application/x-cdlink" },
            { ".vcf", "text/x-vcard" },
            { ".vcg", "application/vnd.groove-vcard" },
            { ".vcs", "text/x-vcalendar" },
            { ".vcx", "application/vnd.vcx" },
            { ".vis", "application/vnd.visionary" },
            { ".viv", "video/vnd.vivo" },
            { ".vor", "application/vnd.stardivision.writer" },
            { ".vox", "application/x-authorware-bin" },
            { ".vrml", "model/vrml" },
            { ".vsd", "application/vnd.visio" },
            { ".vsf", "application/vnd.vsf" },
            { ".vss", "application/vnd.visio" },
            { ".vst", "application/vnd.visio" },
            { ".vsw", "application/vnd.visio" },
            { ".vtu", "model/vnd.vtu" },
            { ".vxml", "application/voicexml+xml" },
            { ".w3d", "application/x-director" },
            { ".wad", "application/x-doom" },
            { ".wasm", "application/wasm" },
            { ".wav", "audio/x-wav" },
            { ".wax", "audio/x-ms-wax" },
            { ".wbmp", "image/vnd.wap.wbmp" },
            { ".wbs", "application/vnd.criticaltools.wbs+xml" },
            { ".wbxml", "application/vnd.wap.wbxml" },
            { ".wcm", "application/vnd.ms-works" },
            { ".wdb", "application/vnd.ms-works" },
            { ".weba", "audio/webm" },
            { ".webm", "video/webm" },
            { ".webp", "image/webp" },
            { ".wiz", "application/msword" },
            { ".wks", "application/vnd.ms-works" },
            { ".wm", "video/x-ms-wm" },
            { ".wma", "audio/x-ms-wma" },
            { ".wmd", "application/x-ms-wmd" },
            { ".wmf", "application/x-msmetafile" },
            { ".wml", "text/vnd.wap.wml" },
            { ".wmlc", "application/vnd.wap.wmlc" },
            { ".wmls", "text/vnd.wap.wmlscript" },
            { ".wmlsc", "application/vnd.wap.wmlscriptc" },
            { ".wmv", "video/x-ms-wmv" },
            { ".wmx", "video/x-ms-wmx" },
            { ".wmz", "application/x-ms-wmz" },
            { ".woff", "font/woff" },
            { ".woff2", "font/woff2" },
            { ".wpd", "application/vnd.wordperfect" },
            { ".wpl", "application/vnd.ms-wpl" },
            { ".wps", "application/vnd.ms-works" },
            { ".wqd", "application/vnd.wqd" },
            { ".wri", "application/x-mswrite" },
            { ".wrl", "model/vrml" },
            { ".wsdl", "application/wsdl+xml" },
            { ".wspolicy", "application/wspolicy+xml" },
            { ".wtb", "application/vnd.webturbo" },
            { ".wvx", "video/x-ms-wvx" },
            { ".x32", "application/x-authorware-bin" },
            { ".x3d", "application/vnd.hzn-3d-crossword" },
            { ".xap", "application/x-silverlight-app" },
            { ".xar", "application/vnd.xara" },
            { ".xbap", "application/x-ms-xbap" },
            { ".xbd", "application/vnd.fujixerox.docuworks.binder" },
            { ".xbm", "image/x-xbitmap" },
            { ".xdm", "application/vnd.syncml.dm+xml" },
            { ".xdp", "application/vnd.adobe.xdp+xml" },
            { ".xdw", "application/vnd.fujixerox.docuworks" },
            { ".xenc", "application/xenc+xml" },
            { ".xer", "application/patch-ops-error+xml" },
            { ".xfdf", "application/vnd.adobe.xfdf" },
            { ".xfdl", "application/vnd.xfdl" },
            { ".xht", "application/xhtml+xml" },
            { ".xhtml", "application/xhtml+xml" },
            { ".xhvml", "application/xv+xml" },
            { ".xif", "image/vnd.xiff" },
            { ".xla", "application/vnd.ms-excel" },
            { ".xlam", "application/vnd.ms-excel.addin.macroenabled.12" },
            { ".xlb", "application/vnd.ms-excel" },
            { ".xlc", "application/vnd.ms-excel" },
            { ".xlm", "application/vnd.ms-excel" },
            { ".xls", "application/vnd.ms-excel" },
            { ".xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12" },
            { ".xlsm", "application/vnd.ms-excel.sheet.macroenabled.12" },
            { ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
            { ".xlt", "application/vnd.ms-excel" },
            { ".xltm", "application/vnd.ms-excel.template.macroenabled.12" },
            { ".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
            { ".xlw", "application/vnd.ms-excel" },
            { ".xml", "application/xml" },
            { ".xo", "application/vnd.olpc-sugar" },
            { ".xop", "application/xop+xml" },
            { ".xpdl", "application/xml" },
            { ".xpi", "application/x-xpinstall" },
            { ".xpm", "image/x-xpixmap" },
            { ".xpr", "application/vnd.is-xpr" },
            { ".xps", "application/vnd.ms-xpsdocument" },
            { ".xpw", "application/vnd.intercon.formnet" },
            { ".xpx", "application/vnd.intercon.formnet" },
            { ".xsl", "application/xml" },
            { ".xslt", "application/xslt+xml" },
            { ".xsm", "application/vnd.syncml+xml" },
            { ".xspf", "application/xspf+xml" },
            { ".xul", "application/vnd.mozilla.xul+xml" },
            { ".xvm", "application/xv+xml" },
            { ".xvml", "application/xv+xml" },
            { ".xwd", "image/x-xwindowdump" },
            { ".xyz", "chemical/x-xyz" },
            { ".yaml", "application/yaml" },
            { ".yml", "application/yaml" },
            { ".zaz", "application/vnd.zzazz.deck+xml" },
            { ".zip", "application/zip" },
            { ".zir", "application/vnd.zul" },
            { ".zirz", "application/vnd.zul" },
            { ".zmm", "application/vnd.handheld-entertainment+xml" },
            { ".zst", "application/zstd" },
        };
    }


    #endregion

    #region Mime Types to File Extensions Maps

    private static IDictionary<string, IEnumerable<string>> PopulateMimeTypeToFileExtensionsMap()
    {
        return new Dictionary<string, IEnumerable<string>>
        {
             { "application/andrew-inset", new[] { ".ez" } },
             { "application/applixware", new[] { ".aw" } },
             { "application/atom+xml", new[] { ".atom" } },
             { "application/atomcat+xml", new[] { ".atomcat" } },
             { "application/atomsvc+xml", new[] { ".atomsvc" } },
             { "application/cbor", new[] { ".cbor" } },
             { "application/ccxml+xml", new[] { ".ccxml" } },
             { "application/cu-seeme", new[] { ".cu" } },
             { "application/davmount+xml", new[] { ".davmount" } },
             { "application/ecmascript", new[] { ".ecma" } },
             { "application/emma+xml", new[] { ".emma" } },
             { "application/epub+zip", new[] { ".epub" } },
             { "application/font-tdpfr", new[] { ".pfr" } },
             { "application/graphql", new[] { ".graphql" } },
             { "application/hyperstudio", new[] { ".stk" } },
             { "application/java-archive", new[] { ".jar" } },
             { "application/java-serialized-object", new[] { ".ser" } },
             { "application/java-vm", new[] { ".class" } },
             { "application/javascript", new[] { ".js" } },
             { "application/json", new[] { ".json" } },
             { "application/ld+json", new[] { ".jsonld" } },
             { "application/lost+xml", new[] { ".lostxml" } },
             { "application/mac-binhex40", new[] { ".hqx" } },
             { "application/mac-compactpro", new[] { ".cpt" } },
             { "application/marc", new[] { ".mrc" } },
             { "application/mathematica", new[] { ".ma", ".mb", ".nb" } },
             { "application/mathml+xml", new[] { ".mathml" } },
             { "application/mbox", new[] { ".mbox" } },
             { "application/mediaservercontrol+xml", new[] { ".mscml" } },
             { "application/mp4", new[] { ".mp4s" } },
             { "application/msword", new[] { ".doc", ".dot", ".wiz" } },
             { "application/mxf", new[] { ".mxf" } },
             { "application/octet-stream", new[] { ".bin", ".a", ".bpk", ".deploy", ".dist", ".distz", ".dmg", ".dms", ".dump", ".elc", ".iso", ".lha", ".lrf", ".lzh", ".o", ".obj", ".pkg", ".so" } },
             { "application/oda", new[] { ".oda" } },
             { "application/oebps-package+xml", new[] { ".opf" } },
             { "application/ogg", new[] { ".ogx" } },
             { "application/onenote", new[] { ".onepkg", ".onetmp", ".onetoc", ".onetoc2" } },
             { "application/patch-ops-error+xml", new[] { ".xer" } },
             { "application/pdf", new[] { ".pdf" } },
             { "application/pgp-encrypted", new[] { ".pgp" } },
             { "application/pgp-signature", new[] { ".asc", ".sig" } },
             { "application/pics-rules", new[] { ".prf" } },
             { "application/pkcs10", new[] { ".p10" } },
             { "application/pkcs7-mime", new[] { ".p7c", ".p7m" } },
             { "application/pkcs7-signature", new[] { ".p7s" } },
             { "application/pkix-cert", new[] { ".cer" } },
             { "application/pkix-crl", new[] { ".crl" } },
             { "application/pkix-pkipath", new[] { ".pkipath" } },
             { "application/pkixcmp", new[] { ".pki" } },
             { "application/pls+xml", new[] { ".pls" } },
             { "application/postscript", new[] { ".ps", ".ai", ".eps" } },
             { "application/prs.cww", new[] { ".cww" } },
             { "application/rdf+xml", new[] { ".rdf" } },
             { "application/reginfo+xml", new[] { ".rif" } },
             { "application/relax-ng-compact-syntax", new[] { ".rnc" } },
             { "application/resource-lists-diff+xml", new[] { ".rld" } },
             { "application/resource-lists+xml", new[] { ".rl" } },
             { "application/rls-services+xml", new[] { ".rs" } },
             { "application/rsd+xml", new[] { ".rsd" } },
             { "application/rss+xml", new[] { ".rss" } },
             { "application/rtf", new[] { ".rtf" } },
             { "application/sbml+xml", new[] { ".sbml" } },
             { "application/scvp-cv-request", new[] { ".scq" } },
             { "application/scvp-cv-response", new[] { ".scs" } },
             { "application/scvp-vp-request", new[] { ".spq" } },
             { "application/scvp-vp-response", new[] { ".spp" } },
             { "application/sdp", new[] { ".sdp" } },
             { "application/set-payment-initiation", new[] { ".setpay" } },
             { "application/set-registration-initiation", new[] { ".setreg" } },
             { "application/shf+xml", new[] { ".shf" } },
             { "application/smil+xml", new[] { ".smi", ".smil" } },
             { "application/sparql-query", new[] { ".rq" } },
             { "application/sparql-results+xml", new[] { ".srx" } },
             { "application/srgs", new[] { ".gram" } },
             { "application/srgs+xml", new[] { ".grxml" } },
             { "application/ssml+xml", new[] { ".ssml" } },
             { "application/vnd.3gpp.pic-bw-large", new[] { ".plb" } },
             { "application/vnd.3gpp.pic-bw-small", new[] { ".psb" } },
             { "application/vnd.3gpp.pic-bw-var", new[] { ".pvb" } },
             { "application/vnd.3gpp2.tcap", new[] { ".tcap" } },
             { "application/vnd.3m.post-it-notes", new[] { ".pwn" } },
             { "application/vnd.accpac.simply.aso", new[] { ".aso" } },
             { "application/vnd.accpac.simply.imp", new[] { ".imp" } },
             { "application/vnd.acucobol", new[] { ".acu" } },
             { "application/vnd.acucorp", new[] { ".acutc", ".atc" } },
             { "application/vnd.adobe.air-application-installer-package+zip", new[] { ".air" } },
             { "application/vnd.adobe.xdp+xml", new[] { ".xdp" } },
             { "application/vnd.adobe.xfdf", new[] { ".xfdf" } },
             { "application/vnd.airzip.filesecure.azf", new[] { ".azf" } },
             { "application/vnd.airzip.filesecure.azs", new[] { ".azs" } },
             { "application/vnd.amazon.ebook", new[] { ".azw" } },
             { "application/vnd.americandynamics.acc", new[] { ".acc" } },
             { "application/vnd.amiga.ami", new[] { ".ami" } },
             { "application/vnd.android.package-archive", new[] { ".apk" } },
             { "application/vnd.anser-web-certificate-issue-initiation", new[] { ".cii" } },
             { "application/vnd.anser-web-funds-transfer-initiation", new[] { ".fti" } },
             { "application/vnd.antix.game-component", new[] { ".atx" } },
             { "application/vnd.apple.installer+xml", new[] { ".mpkg" } },
             { "application/vnd.arastra.swi", new[] { ".swi" } },
             { "application/vnd.audiograph", new[] { ".aep" } },
             { "application/vnd.blueice.multipass", new[] { ".mpm" } },
             { "application/vnd.bmi", new[] { ".bmi" } },
             { "application/vnd.businessobjects", new[] { ".rep" } },
             { "application/vnd.chemdraw+xml", new[] { ".cdxml" } },
             { "application/vnd.chipnuts.karaoke-mmd", new[] { ".mmd" } },
             { "application/vnd.cinderella", new[] { ".cdy" } },
             { "application/vnd.claymore", new[] { ".cla" } },
             { "application/vnd.clonk.c4group", new[] { ".c4d", ".c4f", ".c4g", ".c4p", ".c4u" } },
             { "application/vnd.commonspace", new[] { ".csp" } },
             { "application/vnd.contact.cmsg", new[] { ".cdbcmsg" } },
             { "application/vnd.cosmocaller", new[] { ".cmc" } },
             { "application/vnd.crick.clicker", new[] { ".clkx" } },
             { "application/vnd.crick.clicker.keyboard", new[] { ".clkk" } },
             { "application/vnd.crick.clicker.palette", new[] { ".clkp" } },
             { "application/vnd.crick.clicker.template", new[] { ".clkt" } },
             { "application/vnd.crick.clicker.wordbank", new[] { ".clkw" } },
             { "application/vnd.criticaltools.wbs+xml", new[] { ".wbs" } },
             { "application/vnd.ctc-posml", new[] { ".pml" } },
             { "application/vnd.cups-ppd", new[] { ".ppd" } },
             { "application/vnd.curl.car", new[] { ".car" } },
             { "application/vnd.curl.pcurl", new[] { ".pcurl" } },
             { "application/vnd.data-vision.rdz", new[] { ".rdz" } },
             { "application/vnd.denovo.fcselayout-link", new[] { ".fe_launch" } },
             { "application/vnd.dna", new[] { ".dna" } },
             { "application/vnd.dolby.mlp", new[] { ".mlp" } },
             { "application/vnd.dpgraph", new[] { ".dpg" } },
             { "application/vnd.dreamfactory", new[] { ".dfac" } },
             { "application/vnd.dynageo", new[] { ".geo" } },
             { "application/vnd.ecowin.chart", new[] { ".mag" } },
             { "application/vnd.enliven", new[] { ".nml" } },
             { "application/vnd.epson.esf", new[] { ".esf" } },
             { "application/vnd.epson.msf", new[] { ".msf" } },
             { "application/vnd.epson.quickanime", new[] { ".qam" } },
             { "application/vnd.epson.salt", new[] { ".slt" } },
             { "application/vnd.epson.ssf", new[] { ".ssf" } },
             { "application/vnd.eszigno3+xml", new[] { ".es3", ".et3" } },
             { "application/vnd.ezpix-album", new[] { ".ez2" } },
             { "application/vnd.ezpix-package", new[] { ".ez3" } },
             { "application/vnd.fdf", new[] { ".fdf" } },
             { "application/vnd.fdsn.mseed", new[] { ".mseed" } },
             { "application/vnd.fdsn.seed", new[] { ".dataless", ".seed" } },
             { "application/vnd.flographit", new[] { ".gph" } },
             { "application/vnd.fluxtime.clip", new[] { ".ftc" } },
             { "application/vnd.framemaker", new[] { ".book", ".fm", ".frame", ".maker" } },
             { "application/vnd.frogans.fnc", new[] { ".fnc" } },
             { "application/vnd.frogans.ltf", new[] { ".ltf" } },
             { "application/vnd.fsc.weblaunch", new[] { ".fsc" } },
             { "application/vnd.fujitsu.oasys", new[] { ".oas" } },
             { "application/vnd.fujitsu.oasys2", new[] { ".oa2" } },
             { "application/vnd.fujitsu.oasys3", new[] { ".oa3" } },
             { "application/vnd.fujitsu.oasysgp", new[] { ".fg5" } },
             { "application/vnd.fujitsu.oasysprs", new[] { ".bh2" } },
             { "application/vnd.fujixerox.ddd", new[] { ".ddd" } },
             { "application/vnd.fujixerox.docuworks", new[] { ".xdw" } },
             { "application/vnd.fujixerox.docuworks.binder", new[] { ".xbd" } },
             { "application/vnd.fuzzysheet", new[] { ".fzs" } },
             { "application/vnd.genomatix.tuxedo", new[] { ".txd" } },
             { "application/vnd.geogebra.file", new[] { ".ggb" } },
             { "application/vnd.geogebra.tool", new[] { ".ggt" } },
             { "application/vnd.geometry-explorer", new[] { ".gex", ".gre" } },
             { "application/vnd.gmx", new[] { ".gmx" } },
             { "application/vnd.google-earth.kml+xml", new[] { ".kml" } },
             { "application/vnd.google-earth.kmz", new[] { ".kmz" } },
             { "application/vnd.grafeq", new[] { ".gqf", ".gqs" } },
             { "application/vnd.groove-account", new[] { ".gac" } },
             { "application/vnd.groove-help", new[] { ".ghf" } },
             { "application/vnd.groove-identity-message", new[] { ".gim" } },
             { "application/vnd.groove-injector", new[] { ".grv" } },
             { "application/vnd.groove-tool-message", new[] { ".gtm" } },
             { "application/vnd.groove-tool-template", new[] { ".tpl" } },
             { "application/vnd.groove-vcard", new[] { ".vcg" } },
             { "application/vnd.handheld-entertainment+xml", new[] { ".zmm" } },
             { "application/vnd.hbci", new[] { ".hbci" } },
             { "application/vnd.hhe.lesson-player", new[] { ".les" } },
             { "application/vnd.hp-hpgl", new[] { ".hpgl" } },
             { "application/vnd.hp-hpid", new[] { ".hpid" } },
             { "application/vnd.hp-hps", new[] { ".hps" } },
             { "application/vnd.hp-jlyt", new[] { ".jlt" } },
             { "application/vnd.hp-pcl", new[] { ".pcl" } },
             { "application/vnd.hp-pclxl", new[] { ".pclxl" } },
             { "application/vnd.hydrostatix.sof-data", new[] { ".sfd-hdstx" } },
             { "application/vnd.hzn-3d-crossword", new[] { ".x3d" } },
             { "application/vnd.ibm.minipay", new[] { ".mpy" } },
             { "application/vnd.ibm.modcap", new[] { ".afp", ".list3820", ".listafp" } },
             { "application/vnd.ibm.rights-management", new[] { ".irm" } },
             { "application/vnd.ibm.secure-container", new[] { ".sc" } },
             { "application/vnd.iccprofile", new[] { ".icc", ".icm" } },
             { "application/vnd.igloader", new[] { ".igl" } },
             { "application/vnd.immervision-ivp", new[] { ".ivp" } },
             { "application/vnd.immervision-ivu", new[] { ".ivu" } },
             { "application/vnd.intercon.formnet", new[] { ".xpw", ".xpx" } },
             { "application/vnd.intu.qbo", new[] { ".qbo" } },
             { "application/vnd.intu.qfx", new[] { ".qfx" } },
             { "application/vnd.ipunplugged.rcprofile", new[] { ".rcprofile" } },
             { "application/vnd.irepository.package+xml", new[] { ".irp" } },
             { "application/vnd.is-xpr", new[] { ".xpr" } },
             { "application/vnd.jam", new[] { ".jam" } },
             { "application/vnd.jcp.javame.midlet-rms", new[] { ".rms" } },
             { "application/vnd.jisp", new[] { ".jisp" } },
             { "application/vnd.joost.joda-archive", new[] { ".joda" } },
             { "application/vnd.kahootz", new[] { ".ktr", ".ktz" } },
             { "application/vnd.kde.karbon", new[] { ".karbon" } },
             { "application/vnd.kde.kchart", new[] { ".chrt" } },
             { "application/vnd.kde.kformula", new[] { ".kfo" } },
             { "application/vnd.kde.kivio", new[] { ".flw" } },
             { "application/vnd.kde.kontour", new[] { ".kon" } },
             { "application/vnd.kde.kpresenter", new[] { ".kpr", ".kpt" } },
             { "application/vnd.kde.kspread", new[] { ".ksp" } },
             { "application/vnd.kde.kword", new[] { ".kwd", ".kwt" } },
             { "application/vnd.kenameaapp", new[] { ".htke" } },
             { "application/vnd.kidspiration", new[] { ".kia" } },
             { "application/vnd.kinar", new[] { ".kne", ".knp" } },
             { "application/vnd.koan", new[] { ".skd", ".skm", ".skp", ".skt" } },
             { "application/vnd.kodak-descriptor", new[] { ".sse" } },
             { "application/vnd.llamagraphics.life-balance.desktop", new[] { ".lbd" } },
             { "application/vnd.llamagraphics.life-balance.exchange+xml", new[] { ".lbe" } },
             { "application/vnd.lotus-1-2-3", new[] { ".123" } },
             { "application/vnd.lotus-approach", new[] { ".apr" } },
             { "application/vnd.lotus-freelance", new[] { ".pre" } },
             { "application/vnd.lotus-notes", new[] { ".nsf" } },
             { "application/vnd.lotus-organizer", new[] { ".org" } },
             { "application/vnd.lotus-screencam", new[] { ".scm" } },
             { "application/vnd.lotus-wordpro", new[] { ".lwp" } },
             { "application/vnd.macports.portpkg", new[] { ".portpkg" } },
             { "application/vnd.mcd", new[] { ".mcd" } },
             { "application/vnd.medcalcdata", new[] { ".mc1" } },
             { "application/vnd.mediastation.cdkey", new[] { ".cdkey" } },
             { "application/vnd.mfer", new[] { ".mwf" } },
             { "application/vnd.mfmp", new[] { ".mfm" } },
             { "application/vnd.micrografx.flo", new[] { ".flo" } },
             { "application/vnd.micrografx.igx", new[] { ".igx" } },
             { "application/vnd.mif", new[] { ".mif" } },
             { "application/vnd.mobius.daf", new[] { ".daf" } },
             { "application/vnd.mobius.dis", new[] { ".dis" } },
             { "application/vnd.mobius.mbk", new[] { ".mbk" } },
             { "application/vnd.mobius.mqy", new[] { ".mqy" } },
             { "application/vnd.mobius.msl", new[] { ".msl" } },
             { "application/vnd.mobius.plc", new[] { ".plc" } },
             { "application/vnd.mobius.txf", new[] { ".txf" } },
             { "application/vnd.mophun.application", new[] { ".mpn" } },
             { "application/vnd.mophun.certificate", new[] { ".mpc" } },
             { "application/vnd.mozilla.xul+xml", new[] { ".xul" } },
             { "application/vnd.ms-artgalry", new[] { ".cil" } },
             { "application/vnd.ms-cab-compressed", new[] { ".cab" } },
             { "application/vnd.ms-excel", new[] { ".xls", ".xla", ".xlb", ".xlc", ".xlm", ".xlt", ".xlw" } },
             { "application/vnd.ms-excel.addin.macroenabled.12", new[] { ".xlam" } },
             { "application/vnd.ms-excel.sheet.binary.macroenabled.12", new[] { ".xlsb" } },
             { "application/vnd.ms-excel.sheet.macroenabled.12", new[] { ".xlsm" } },
             { "application/vnd.ms-excel.template.macroenabled.12", new[] { ".xltm" } },
             { "application/vnd.ms-fontobject", new[] { ".eot" } },
             { "application/vnd.ms-htmlhelp", new[] { ".chm" } },
             { "application/vnd.ms-ims", new[] { ".ims" } },
             { "application/vnd.ms-lrm", new[] { ".lrm" } },
             { "application/vnd.ms-pki.seccat", new[] { ".cat" } },
             { "application/vnd.ms-pki.stl", new[] { ".stl" } },
             { "application/vnd.ms-powerpoint", new[] { ".ppt", ".pot", ".ppa", ".pps", ".pwz" } },
             { "application/vnd.ms-powerpoint.addin.macroenabled.12", new[] { ".ppam" } },
             { "application/vnd.ms-powerpoint.presentation.macroenabled.12", new[] { ".pptm" } },
             { "application/vnd.ms-powerpoint.slide.macroenabled.12", new[] { ".sldm" } },
             { "application/vnd.ms-powerpoint.slideshow.macroenabled.12", new[] { ".ppsm" } },
             { "application/vnd.ms-powerpoint.template.macroenabled.12", new[] { ".potm" } },
             { "application/vnd.ms-project", new[] { ".mpp", ".mpt" } },
             { "application/vnd.ms-word.document.macroenabled.12", new[] { ".docm" } },
             { "application/vnd.ms-word.template.macroenabled.12", new[] { ".dotm" } },
             { "application/vnd.ms-works", new[] { ".wcm", ".wdb", ".wks", ".wps" } },
             { "application/vnd.ms-wpl", new[] { ".wpl" } },
             { "application/vnd.ms-xpsdocument", new[] { ".xps" } },
             { "application/vnd.mseq", new[] { ".mseq" } },
             { "application/vnd.musician", new[] { ".mus" } },
             { "application/vnd.muvee.style", new[] { ".msty" } },
             { "application/vnd.neurolanguage.nlu", new[] { ".nlu" } },
             { "application/vnd.noblenet-directory", new[] { ".nnd" } },
             { "application/vnd.noblenet-sealer", new[] { ".nns" } },
             { "application/vnd.noblenet-web", new[] { ".nnw" } },
             { "application/vnd.nokia.n-gage.data", new[] { ".ngdat" } },
             { "application/vnd.nokia.n-gage.symbian.install", new[] { ".n-gage" } },
             { "application/vnd.nokia.radio-preset", new[] { ".rpst" } },
             { "application/vnd.nokia.radio-presets", new[] { ".rpss" } },
             { "application/vnd.novadigm.edm", new[] { ".edm" } },
             { "application/vnd.novadigm.edx", new[] { ".edx" } },
             { "application/vnd.novadigm.ext", new[] { ".ext" } },
             { "application/vnd.oasis.opendocument.chart", new[] { ".odc" } },
             { "application/vnd.oasis.opendocument.chart-template", new[] { ".otc" } },
             { "application/vnd.oasis.opendocument.database", new[] { ".odb" } },
             { "application/vnd.oasis.opendocument.formula", new[] { ".odf" } },
             { "application/vnd.oasis.opendocument.formula-template", new[] { ".odft" } },
             { "application/vnd.oasis.opendocument.graphics", new[] { ".odg" } },
             { "application/vnd.oasis.opendocument.graphics-template", new[] { ".otg" } },
             { "application/vnd.oasis.opendocument.image", new[] { ".odi" } },
             { "application/vnd.oasis.opendocument.image-template", new[] { ".oti" } },
             { "application/vnd.oasis.opendocument.presentation", new[] { ".odp" } },
             { "application/vnd.oasis.opendocument.presentation-template", new[] { ".otp" } },
             { "application/vnd.oasis.opendocument.spreadsheet", new[] { ".ods" } },
             { "application/vnd.oasis.opendocument.spreadsheet-template", new[] { ".ots" } },
             { "application/vnd.oasis.opendocument.text", new[] { ".odt" } },
             { "application/vnd.oasis.opendocument.text-master", new[] { ".otm" } },
             { "application/vnd.oasis.opendocument.text-template", new[] { ".ott" } },
             { "application/vnd.oasis.opendocument.text-web", new[] { ".oth" } },
             { "application/vnd.olpc-sugar", new[] { ".xo" } },
             { "application/vnd.oma.dd2+xml", new[] { ".dd2" } },
             { "application/vnd.openofficeorg.extension", new[] { ".oxt" } },
             { "application/vnd.openxmlformats-officedocument.presentationml.presentation", new[] { ".pptx" } },
             { "application/vnd.openxmlformats-officedocument.presentationml.slide", new[] { ".sldx" } },
             { "application/vnd.openxmlformats-officedocument.presentationml.slideshow", new[] { ".ppsx" } },
             { "application/vnd.openxmlformats-officedocument.presentationml.template", new[] { ".potx" } },
             { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", new[] { ".xlsx" } },
             { "application/vnd.openxmlformats-officedocument.spreadsheetml.template", new[] { ".xltx" } },
             { "application/vnd.openxmlformats-officedocument.wordprocessingml.document", new[] { ".docx" } },
             { "application/vnd.openxmlformats-officedocument.wordprocessingml.template", new[] { ".dotx" } },
             { "application/vnd.osgi.dp", new[] { ".dp" } },
             { "application/vnd.palm", new[] { ".oprc", ".pdb", ".pqa" } },
             { "application/vnd.pg.format", new[] { ".str" } },
             { "application/vnd.pg.osasli", new[] { ".ei6" } },
             { "application/vnd.picsel", new[] { ".efif" } },
             { "application/vnd.pocketlearn", new[] { ".plf" } },
             { "application/vnd.powerbuilder6", new[] { ".pbd" } },
             { "application/vnd.previewsystems.box", new[] { ".box" } },
             { "application/vnd.proteus.magazine", new[] { ".mgz" } },
             { "application/vnd.publishare-delta-tree", new[] { ".qps" } },
             { "application/vnd.pvi.ptid1", new[] { ".ptid" } },
             { "application/vnd.quark.quarkxpress", new[] { ".qwd", ".qwt", ".qxb", ".qxd", ".qxl", ".qxt" } },
             { "application/vnd.recordare.musicxml", new[] { ".mxl" } },
             { "application/vnd.recordare.musicxml+xml", new[] { ".musicxml" } },
             { "application/vnd.rim.cod", new[] { ".cod" } },
             { "application/vnd.rn-realmedia", new[] { ".rm" } },
             { "application/vnd.route66.link66+xml", new[] { ".link66" } },
             { "application/vnd.seemail", new[] { ".see" } },
             { "application/vnd.sema", new[] { ".sema" } },
             { "application/vnd.semd", new[] { ".semd" } },
             { "application/vnd.semf", new[] { ".semf" } },
             { "application/vnd.shana.informed.formdata", new[] { ".ifm" } },
             { "application/vnd.shana.informed.formtemplate", new[] { ".itp" } },
             { "application/vnd.shana.informed.interchange", new[] { ".iif" } },
             { "application/vnd.shana.informed.package", new[] { ".ipk" } },
             { "application/vnd.simtech-mindmapper", new[] { ".twd", ".twds" } },
             { "application/vnd.smaf", new[] { ".mmf" } },
             { "application/vnd.smart.teacher", new[] { ".teacher" } },
             { "application/vnd.solent.sdkm+xml", new[] { ".sdkd", ".sdkm" } },
             { "application/vnd.spotfire.dxp", new[] { ".dxp" } },
             { "application/vnd.spotfire.sfs", new[] { ".sfs" } },
             { "application/vnd.stardivision.calc", new[] { ".sdc" } },
             { "application/vnd.stardivision.draw", new[] { ".sda" } },
             { "application/vnd.stardivision.impress", new[] { ".sdd" } },
             { "application/vnd.stardivision.math", new[] { ".smf" } },
             { "application/vnd.stardivision.writer", new[] { ".sdw", ".vor" } },
             { "application/vnd.stardivision.writer-global", new[] { ".sgl" } },
             { "application/vnd.sun.xml.calc", new[] { ".sxc" } },
             { "application/vnd.sun.xml.calc.template", new[] { ".stc" } },
             { "application/vnd.sun.xml.draw", new[] { ".sxd" } },
             { "application/vnd.sun.xml.draw.template", new[] { ".std" } },
             { "application/vnd.sun.xml.impress", new[] { ".sxi" } },
             { "application/vnd.sun.xml.impress.template", new[] { ".sti" } },
             { "application/vnd.sun.xml.math", new[] { ".sxm" } },
             { "application/vnd.sun.xml.writer", new[] { ".sxw" } },
             { "application/vnd.sun.xml.writer.global", new[] { ".sxg" } },
             { "application/vnd.sun.xml.writer.template", new[] { ".stw" } },
             { "application/vnd.sus-calendar", new[] { ".sus", ".susp" } },
             { "application/vnd.svd", new[] { ".svd" } },
             { "application/vnd.symbian.install", new[] { ".sis", ".sisx" } },
             { "application/vnd.syncml.dm+wbxml", new[] { ".bdm" } },
             { "application/vnd.syncml.dm+xml", new[] { ".xdm" } },
             { "application/vnd.syncml+xml", new[] { ".xsm" } },
             { "application/vnd.tao.intent-module-archive", new[] { ".tao" } },
             { "application/vnd.tmobile-livetv", new[] { ".tmo" } },
             { "application/vnd.trid.tpt", new[] { ".tpt" } },
             { "application/vnd.triscape.mxs", new[] { ".mxs" } },
             { "application/vnd.trueapp", new[] { ".tra" } },
             { "application/vnd.ufdl", new[] { ".ufd", ".ufdl" } },
             { "application/vnd.uiq.theme", new[] { ".utz" } },
             { "application/vnd.umajin", new[] { ".umj" } },
             { "application/vnd.unity", new[] { ".unityweb" } },
             { "application/vnd.uoml+xml", new[] { ".uoml" } },
             { "application/vnd.vcx", new[] { ".vcx" } },
             { "application/vnd.visio", new[] { ".vsd", ".vss", ".vst", ".vsw" } },
             { "application/vnd.visionary", new[] { ".vis" } },
             { "application/vnd.vsf", new[] { ".vsf" } },
             { "application/vnd.wap.sic", new[] { ".sic" } },
             { "application/vnd.wap.slc", new[] { ".slc" } },
             { "application/vnd.wap.wbxml", new[] { ".wbxml" } },
             { "application/vnd.wap.wmlc", new[] { ".wmlc" } },
             { "application/vnd.wap.wmlscriptc", new[] { ".wmlsc" } },
             { "application/vnd.webturbo", new[] { ".wtb" } },
             { "application/vnd.wordperfect", new[] { ".wpd" } },
             { "application/vnd.wqd", new[] { ".wqd" } },
             { "application/vnd.wt.stf", new[] { ".stf" } },
             { "application/vnd.xara", new[] { ".xar" } },
             { "application/vnd.xfdl", new[] { ".xfdl" } },
             { "application/vnd.yamaha.hv-dic", new[] { ".hvd" } },
             { "application/vnd.yamaha.hv-script", new[] { ".hvs" } },
             { "application/vnd.yamaha.hv-voice", new[] { ".hvp" } },
             { "application/vnd.yamaha.openscoreformat", new[] { ".osf" } },
             { "application/vnd.yamaha.openscoreformat.osfpvg+xml", new[] { ".osfpvg" } },
             { "application/vnd.yamaha.smaf-audio", new[] { ".saf" } },
             { "application/vnd.yamaha.smaf-phrase", new[] { ".spf" } },
             { "application/vnd.yellowriver-custom-menu", new[] { ".cmp" } },
             { "application/vnd.zul", new[] { ".zir", ".zirz" } },
             { "application/vnd.zzazz.deck+xml", new[] { ".zaz" } },
             { "application/voicexml+xml", new[] { ".vxml" } },
             { "application/wasm", new[] { ".wasm" } },
             { "application/winhlp", new[] { ".hlp" } },
             { "application/wsdl+xml", new[] { ".wsdl" } },
             { "application/wspolicy+xml", new[] { ".wspolicy" } },
             { "application/x-7z-compressed", new[] { ".7z" } },
             { "application/x-abiword", new[] { ".abw" } },
             { "application/x-ace-compressed", new[] { ".ace" } },
             { "application/x-authorware-bin", new[] { ".aab", ".u32", ".vox", ".x32" } },
             { "application/x-authorware-map", new[] { ".aam" } },
             { "application/x-authorware-seg", new[] { ".aas" } },
             { "application/x-bcpio", new[] { ".bcpio" } },
             { "application/x-bittorrent", new[] { ".torrent" } },
             { "application/x-bzip", new[] { ".bz" } },
             { "application/x-bzip2", new[] { ".boz", ".bz2" } },
             { "application/x-cdlink", new[] { ".vcd" } },
             { "application/x-chat", new[] { ".chat" } },
             { "application/x-chess-pgn", new[] { ".pgn" } },
             { "application/x-cpio", new[] { ".cpio" } },
             { "application/x-csh", new[] { ".csh" } },
             { "application/x-debian-package", new[] { ".deb", ".udeb" } },
             { "application/x-director", new[] { ".cct", ".cst", ".cxt", ".dcr", ".dir", ".dxr", ".fgd", ".swa", ".w3d" } },
             { "application/x-doom", new[] { ".wad" } },
             { "application/x-dtbncx+xml", new[] { ".ncx" } },
             { "application/x-dtbook+xml", new[] { ".dtb" } },
             { "application/x-dtbresource+xml", new[] { ".res" } },
             { "application/x-dvi", new[] { ".dvi" } },
             { "application/x-font-bdf", new[] { ".bdf" } },
             { "application/x-font-ghostscript", new[] { ".gsf" } },
             { "application/x-font-linux-psf", new[] { ".psf" } },
             { "application/x-font-otf", new[] { ".otf" } },
             { "application/x-font-pcf", new[] { ".pcf" } },
             { "application/x-font-snf", new[] { ".snf" } },
             { "application/x-font-ttf", new[] { ".ttc", ".ttf" } },
             { "application/x-font-type1", new[] { ".afm", ".pfa", ".pfb", ".pfm" } },
             { "application/x-futuresplash", new[] { ".spl" } },
             { "application/x-gnumeric", new[] { ".gnumeric" } },
             { "application/x-gtar", new[] { ".gtar" } },
             { "application/x-gzip", new[] { ".gz", ".tgz" } },
             { "application/x-hdf", new[] { ".hdf" } },
             { "application/x-java-jnlp-file", new[] { ".jnlp" } },
             { "application/x-killustrator", new[] { ".kil" } },
             { "application/x-latex", new[] { ".latex" } },
             { "application/x-mobipocket-ebook", new[] { ".mobi", ".prc" } },
             { "application/x-ms-application", new[] { ".application" } },
             { "application/x-ms-wmd", new[] { ".wmd" } },
             { "application/x-ms-wmz", new[] { ".wmz" } },
             { "application/x-ms-xbap", new[] { ".xbap" } },
             { "application/x-msaccess", new[] { ".mdb" } },
             { "application/x-msbinder", new[] { ".obd" } },
             { "application/x-mscardfile", new[] { ".crd" } },
             { "application/x-msclip", new[] { ".clp" } },
             { "application/x-msdownload", new[] { ".bat", ".com", ".dll", ".exe", ".msi" } },
             { "application/x-msmediaview", new[] { ".m13", ".m14", ".mvb" } },
             { "application/x-msmetafile", new[] { ".wmf" } },
             { "application/x-msmoney", new[] { ".mny" } },
             { "application/x-mspublisher", new[] { ".pub" } },
             { "application/x-msschedule", new[] { ".scd" } },
             { "application/x-msterminal", new[] { ".trm" } },
             { "application/x-mswrite", new[] { ".wri" } },
             { "application/x-netcdf", new[] { ".cdf", ".nc" } },
             { "application/x-pkcs12", new[] { ".p12", ".pfx" } },
             { "application/x-pkcs7-certificates", new[] { ".p7b", ".spc" } },
             { "application/x-pkcs7-certreqresp", new[] { ".p7r" } },
             { "application/x-python-code", new[] { ".pyc", ".pyo" } },
             { "application/x-rar-compressed", new[] { ".rar" } },
             { "application/x-rpm", new[] { ".rpm" } },
             { "application/x-sh", new[] { ".sh" } },
             { "application/x-shar", new[] { ".shar" } },
             { "application/x-shockwave-flash", new[] { ".swf" } },
             { "application/x-silverlight-app", new[] { ".xap" } },
             { "application/x-stuffit", new[] { ".sit" } },
             { "application/x-stuffitx", new[] { ".sitx" } },
             { "application/x-sv4cpio", new[] { ".sv4cpio" } },
             { "application/x-sv4crc", new[] { ".sv4crc" } },
             { "application/x-tar", new[] { ".tar" } },
             { "application/x-tcl", new[] { ".tcl" } },
             { "application/x-tex", new[] { ".tex" } },
             { "application/x-tex-tfm", new[] { ".tfm" } },
             { "application/x-texinfo", new[] { ".texi", ".texinfo" } },
             { "application/x-ustar", new[] { ".ustar" } },
             { "application/x-wais-source", new[] { ".src" } },
             { "application/x-x509-ca-cert", new[] { ".crt", ".der" } },
             { "application/x-xfig", new[] { ".fig" } },
             { "application/x-xpinstall", new[] { ".xpi" } },
             { "application/xenc+xml", new[] { ".xenc" } },
             { "application/xhtml+xml", new[] { ".xht", ".xhtml" } },
             { "application/xml", new[] { ".xml", ".xpdl", ".xsl" } },
             { "application/xml-dtd", new[] { ".dtd" } },
             { "application/xop+xml", new[] { ".xop" } },
             { "application/xslt+xml", new[] { ".xslt" } },
             { "application/xspf+xml", new[] { ".xspf" } },
             { "application/xv+xml", new[] { ".mxml", ".xhvml", ".xvm", ".xvml" } },
             { "application/yaml", new[] { ".yaml", ".yml" } },
             { "application/zip", new[] { ".zip" } },
             { "application/zstd", new[] { ".zst" } },
             { "audio/adpcm", new[] { ".adp" } },
             { "audio/basic", new[] { ".au", ".snd" } },
             { "audio/flac", new[] { ".flac" } },
             { "audio/midi", new[] { ".midi", ".kar", ".mid", ".rmi" } },
             { "audio/mp4", new[] { ".mp4a" } },
             { "audio/mpeg", new[] { ".mp3", ".m2a", ".m3a", ".mp2", ".mp2a", ".mpga" } },
             { "audio/ogg", new[] { ".ogg", ".oga", ".spx" } },
             { "audio/vnd.digital-winds", new[] { ".eol" } },
             { "audio/vnd.dts", new[] { ".dts" } },
             { "audio/vnd.dts.hd", new[] { ".dtshd" } },
             { "audio/vnd.lucent.voice", new[] { ".lvp" } },
             { "audio/vnd.ms-playready.media.pya", new[] { ".pya" } },
             { "audio/vnd.nuera.ecelp4800", new[] { ".ecelp4800" } },
             { "audio/vnd.nuera.ecelp7470", new[] { ".ecelp7470" } },
             { "audio/vnd.nuera.ecelp9600", new[] { ".ecelp9600" } },
             { "audio/webm", new[] { ".weba" } },
             { "audio/x-aac", new[] { ".aac" } },
             { "audio/x-aiff", new[] { ".aiff", ".aif", ".aifc" } },
             { "audio/x-mpegurl", new[] { ".m3u" } },
             { "audio/x-ms-wax", new[] { ".wax" } },
             { "audio/x-ms-wma", new[] { ".wma" } },
             { "audio/x-pn-realaudio", new[] { ".ra", ".ram" } },
             { "audio/x-pn-realaudio-plugin", new[] { ".rmp" } },
             { "audio/x-wav", new[] { ".wav" } },
             { "chemical/x-cdx", new[] { ".cdx" } },
             { "chemical/x-cif", new[] { ".cif" } },
             { "chemical/x-cmdf", new[] { ".cmdf" } },
             { "chemical/x-cml", new[] { ".cml" } },
             { "chemical/x-csml", new[] { ".csml" } },
             { "chemical/x-xyz", new[] { ".xyz" } },
             { "font/woff", new[] { ".woff" } },
             { "font/woff2", new[] { ".woff2" } },
             { "image/avif", new[] { ".avif" } },
             { "image/bmp", new[] { ".bmp" } },
             { "image/cgm", new[] { ".cgm" } },
             { "image/g3fax", new[] { ".g3" } },
             { "image/gif", new[] { ".gif" } },
             { "image/heic", new[] { ".heic" } },
             { "image/heif", new[] { ".heif" } },
             { "image/ief", new[] { ".ief" } },
             { "image/jpeg", new[] { ".jpg", ".jpe", ".jpeg" } },
             { "image/png", new[] { ".png" } },
             { "image/prs.btif", new[] { ".btif" } },
             { "image/svg+xml", new[] { ".svg", ".svgz" } },
             { "image/tiff", new[] { ".tif", ".tiff" } },
             { "image/vnd.adobe.photoshop", new[] { ".psd" } },
             { "image/vnd.djvu", new[] { ".djv", ".djvu" } },
             { "image/vnd.dwg", new[] { ".dwg" } },
             { "image/vnd.dxf", new[] { ".dxf" } },
             { "image/vnd.fastbidsheet", new[] { ".fbs" } },
             { "image/vnd.fpx", new[] { ".fpx" } },
             { "image/vnd.fst", new[] { ".fst" } },
             { "image/vnd.fujixerox.edmics-mmr", new[] { ".mmr" } },
             { "image/vnd.fujixerox.edmics-rlc", new[] { ".rlc" } },
             { "image/vnd.ms-modi", new[] { ".mdi" } },
             { "image/vnd.net-fpx", new[] { ".npx" } },
             { "image/vnd.wap.wbmp", new[] { ".wbmp" } },
             { "image/vnd.xiff", new[] { ".xif" } },
             { "image/webp", new[] { ".webp" } },
             { "image/x-cmu-raster", new[] { ".ras" } },
             { "image/x-cmx", new[] { ".cmx" } },
             { "image/x-freehand", new[] { ".fh", ".fh4", ".fh5", ".fh7", ".fhc" } },
             { "image/x-icon", new[] { ".ico" } },
             { "image/x-pcx", new[] { ".pcx" } },
             { "image/x-pict", new[] { ".pct", ".pic" } },
             { "image/x-portable-anymap", new[] { ".pnm" } },
             { "image/x-portable-bitmap", new[] { ".pbm" } },
             { "image/x-portable-graymap", new[] { ".pgm" } },
             { "image/x-portable-pixmap", new[] { ".ppm" } },
             { "image/x-rgb", new[] { ".rgb" } },
             { "image/x-xbitmap", new[] { ".xbm" } },
             { "image/x-xpixmap", new[] { ".xpm" } },
             { "image/x-xwindowdump", new[] { ".xwd" } },
             { "message/rfc822", new[] { ".eml", ".mht", ".mhtml", ".mime", ".nws" } },
             { "model/iges", new[] { ".iges", ".igs" } },
             { "model/mesh", new[] { ".mesh", ".msh", ".silo" } },
             { "model/vnd.dwf", new[] { ".dwf" } },
             { "model/vnd.gdl", new[] { ".gdl" } },
             { "model/vnd.gtw", new[] { ".gtw" } },
             { "model/vnd.mts", new[] { ".mts" } },
             { "model/vnd.vtu", new[] { ".vtu" } },
             { "model/vrml", new[] { ".vrml", ".wrl" } },
             { "text/calendar", new[] { ".ics", ".ifb" } },
             { "text/css", new[] { ".css" } },
             { "text/csv", new[] { ".csv" } },
             { "text/html", new[] { ".htm", ".html" } },
             { "text/plain", new[] { ".txt", ".conf", ".def", ".diff", ".in", ".ksh", ".list", ".log", ".pl", ".text" } },
             { "text/prs.lines.tag", new[] { ".dsc" } },
             { "text/richtext", new[] { ".rtx" } },
             { "text/sgml", new[] { ".sgm", ".sgml" } },
             { "text/tab-separated-values", new[] { ".tsv" } },
             { "text/troff", new[] { ".man", ".me", ".ms", ".roff", ".t", ".tr" } },
             { "text/uri-list", new[] { ".uri", ".uris", ".urls" } },
             { "text/vnd.curl", new[] { ".curl" } },
             { "text/vnd.curl.dcurl", new[] { ".dcurl" } },
             { "text/vnd.curl.mcurl", new[] { ".mcurl" } },
             { "text/vnd.curl.scurl", new[] { ".scurl" } },
             { "text/vnd.fly", new[] { ".fly" } },
             { "text/vnd.fmi.flexstor", new[] { ".flx" } },
             { "text/vnd.graphviz", new[] { ".gv" } },
             { "text/vnd.in3d.3dml", new[] { ".3dml" } },
             { "text/vnd.in3d.spot", new[] { ".spot" } },
             { "text/vnd.sun.j2me.app-descriptor", new[] { ".jad" } },
             { "text/vnd.wap.si", new[] { ".si" } },
             { "text/vnd.wap.sl", new[] { ".sl" } },
             { "text/vnd.wap.wml", new[] { ".wml" } },
             { "text/vnd.wap.wmlscript", new[] { ".wmls" } },
             { "text/x-asm", new[] { ".asm", ".s" } },
             { "text/x-c", new[] { ".c", ".cc", ".cpp", ".cxx", ".dic", ".h", ".hh" } },
             { "text/x-fortran", new[] { ".f", ".f77", ".f90", ".for" } },
             { "text/x-java-source", new[] { ".java" } },
             { "text/x-pascal", new[] { ".p", ".pas" } },
             { "text/x-python", new[] { ".py" } },
             { "text/x-setext", new[] { ".etx" } },
             { "text/x-uuencode", new[] { ".uu" } },
             { "text/x-vcalendar", new[] { ".vcs" } },
             { "text/x-vcard", new[] { ".vcf" } },
             { "video/3gpp", new[] { ".3gp" } },
             { "video/3gpp2", new[] { ".3g2" } },
             { "video/h261", new[] { ".h261" } },
             { "video/h263", new[] { ".h263" } },
             { "video/h264", new[] { ".h264" } },
             { "video/jpeg", new[] { ".jpgv" } },
             { "video/jpm", new[] { ".jpgm", ".jpm" } },
             { "video/mj2", new[] { ".mj2", ".mjp2" } },
             { "video/mp4", new[] { ".mp4", ".mp4v", ".mpg4" } },
             { "video/mpeg", new[] { ".mpeg", ".m1v", ".m2v", ".mpa", ".mpe", ".mpg" } },
             { "video/ogg", new[] { ".ogv" } },
             { "video/quicktime", new[] { ".mov", ".qt" } },
             { "video/vnd.fvt", new[] { ".fvt" } },
             { "video/vnd.mpegurl", new[] { ".m4u", ".mxu" } },
             { "video/vnd.ms-playready.media.pyv", new[] { ".pyv" } },
             { "video/vnd.vivo", new[] { ".viv" } },
             { "video/webm", new[] { ".webm" } },
             { "video/x-f4v", new[] { ".f4v" } },
             { "video/x-fli", new[] { ".fli" } },
             { "video/x-flv", new[] { ".flv" } },
             { "video/x-m4v", new[] { ".m4v" } },
             { "video/x-ms-asf", new[] { ".asf", ".asx" } },
             { "video/x-ms-wm", new[] { ".wm" } },
             { "video/x-ms-wmv", new[] { ".wmv" } },
             { "video/x-ms-wmx", new[] { ".wmx" } },
             { "video/x-ms-wvx", new[] { ".wvx" } },
             { "video/x-msvideo", new[] { ".avi" } },
             { "video/x-sgi-movie", new[] { ".movie" } },
             { "x-conference/x-cooltalk", new[] { ".ice" } },
        };
    }

    #endregion
}

#pragma warning restore S1192 // String literals should not be duplicated